# Generated by Django 3.2.7 on 2021-09-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='LastDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
